version: "3.0"

services:
  broker-service:
    build:
      context: ./broker-service
      target: debugger 
    restart: always
    volumes:
      - ./broker-service:/home/app
    ports:
      - "8080:8000"
      - "2001:2345"
    security_opt:
      - seccomp:unconfined
    deploy:
      mode: replicated
      replicas: 1
  authentication-service:
    build:
      context: ./authentication-service
      target: debugger 
    restart: always
    volumes:
      - ./authentication-service:/home/app
    ports:
      - "8081:8000"
      - "2002:2345"
    security_opt:
      - seccomp:unconfined
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable connect_timeout=10"
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/